Add files via upload

diff --git a/filter-tick-cat/tradelog b/filter-tick-cat/tradelog
--- a/filter-tick-cat/tradelog
+++ b/filter-tick-cat/tradelog
@@ -1,233 +1,135 @@
 #!/bin/bash
+
 export POSIXLY_CORRECT=yes
 export LC_NUMERIC=en_US.UTF-8
-export LC_ALL=C
 
-
-function printHelp ()
+#prints help
+help()
 {
-  echo "–––––––––––––––––––"
-  echo "     TRADELOG      " 
-  echo "–––––––––––––––––––"
-  echo "analyzátor logů z obchodování na burze"
-  echo ""
-  echo "POUŽITÍ"
-  echo "–––––––––––"
-  echo "tradelog [-h|--help] [FILTR] [PŘÍKAZ] [LOG [LOG2 [...]]"
-  echo ""
-
-  echo "PŘÍKAZY"
-  echo "----------"
-  echo "list-tick"
-  echo "   výpis seznamu vyskytujících se burzovních symbolů, tzv. “tickerů”."
-  echo ""
-
-  echo "profit"
-  echo "   výpis celkového zisku z uzavřených pozic."
-  echo ""
-
-
-  echo "pos"
-  echo "   výpis hodnot aktuálně držených pozic seřazených sestupně dle hodnoty."
-  echo ""
-
-  echo "last-price"
-  echo "   výpis poslední známé ceny pro každý ticker."
-  echo ""
- 
-  echo "hist-ord"
-  echo "   výpis histogramu počtu transakcí dle tickeru."
-  echo ""
- 
-  echo "graph-pos"
-  echo "   výpis grafu hodnot držených pozic dle tickeru."
-  echo ""
-  echo ""
-
-  echo "FILTRY"
-  echo "----------"
-  echo "filtr může být jeden, ale i kombinace následujících"
-  echo ""
-
-  echo "-a DATETIME"
-  echo "   jsou uvažovány pouze záznamy PO tomto datu (bez tohoto data). DATETIME je formátu YYYY-MM-DD HH:MM:SS."
-  echo ""
-
-  echo "-b DATETIME"
-  echo "   jsou uvažovány pouze záznamy PŘED tímto datem (bez tohoto data). DATETIME je formátu YYYY-MM-DD HH:MM:SS."
-  echo ""
-
-  echo "-t TICKER"
-  echo "   jsou uvažovány pouze záznamy odpovídající danému tickeru. Při více výskytech přepínače se bere množina všech uvedených tickerů."
-  echo ""
-
-  echo "-w WIDTH "
-  echo "   u výpisu grafů nastavuje jejich šířku, tedy délku nejdelšího řádku na WIDTH. Tedy, WIDTH musí být kladné celé číslo. Více výskytů přepínače je chybné spuštění."
-  echo ""
-
-  echo "-h a --help "
-  echo "   vypíšou nápovědu s krátkým popisem každého příkazu a přepínače."
-
+echo ""
+echo "USAGE"
+echo "tradelog [-h|--help] [FILTR] [PŘÍKAZ] [LOG [LOG2 [...]]"
+echo ""
+echo "COMMANDS"
+echo "list-tick – prints list of tickers"
+echo "profit – prints profit from all holded positions"
+echo "pos – prints value of currently holded positions"
+echo "last-price – last known price for every ticker"
+echo "hist-ord – prints histogram of number of transactions for every ticker"
+echo "graph-pos – prints graph of values of currently holded positions"
+echo ""
+echo "FILTERS"
+echo "-a DATETIME – after: logs after this date only"
+echo "-b DATETIME – before: logs before this date only"
+echo "-t TICKER – logs only with this ticker"
+echo "-w WIDTH – width of printed graph (optional)"
+echo "-h | --help – prints this"
+echo ""
 }
 
-args=("$@") #načte všechny argumenty
-argsCount=${#args[@]} #počet argumentů
-tickerArray=()
-tickerFilter=false
-src="cat " #fallback
-noFilter=true
-singleFile=true
+#variables inicialization
+command=""
+ticker_filter=""
+log_files=""
+gz_files=""
+daytime_after="0000-00-00 00:00:00"
+daytime_before="9999-99-99 99:99:99"
+width=0
 
-printCol=0 #určení jaké sloupce se budou zobrazovat na výstup. Implicitně vytiskne všechny ($0)
+if [ "$#" = "0" ]
+then
+   cat -
+   exit 0
+fi
 
- 
-#loop který prochází argumenty
-j=0
-for (( i=0;i<$argsCount;i++)); do 
-
-  if [ "${args[${i}]}" == "--help" ] || [ "${args[${i}]}" == "-h" ]; then
-    printHelp
-    exit 1
-  fi
-
-  if [ "${args[${i}]}" == "-a" ]; then
-    tickerFilter=true
-    after="${args[${i}+1]}"
-    filtrDate+=" && \$1 > \""$after"\""
-  fi
-
-  if [ "${args[${i}]}" == "-b" ]; then
-    tickerFilter=true
-    before="${args[${i}+1]}"
-    filtrDate+=" && \$1 < \""$before"\""
-  fi
-
-  if [ "${args[${i}]}" == "-t" ]; then
-    tickerArray[$j]=${args[${i}+1]}
-    j=$((j+1))
-    i=$((i+1)) #když narazíš na -t, tak nahraj ticker do poleTickerů a skoč tentokrát ob jeden prvek
-    tickerFilter=true
-  fi
-
-  if [ "${args[${i}]}" == "-w" ]; then
-    width=${args[${i}+1]}
-  fi
-
-  #pomocí regulárního výrazu hledá cokoliv, co má příponu .log
-  if [[ ${args[${i}]}  =~ ^.+\.(log)$ ]]; then
-    if [ "$singleFile" == "true" ]; then
-      src="cat "${args[${i}]} 
-      singleFile=false
-    else
-      src+=" "${args[${i}]}
-    fi  
-  fi  
-
-  #pomocí regulárního výrazu hledá cokoliv, co má příponu .log.gz
-  if [[ ${args[${i}]}  =~ ^.+\.(log.gz)$ ]]; then
-    src="gzip -d -c "${args[${i}]}
-    singleFile=false
-  fi    
-
-  if [ "${args[${i}]}" == "list-tick" ]; then
-    tickerFilter=true
-    printCol=2 #program vytiskne pouze sloupec, ve kterém jsou tickery
-    listTick=true
-  fi
-
-  if [ "${args[${i}]}" == "profit" ]; then
-    noFilter=false
-    tickerFilter=true
-    profitFilter=true
-  fi
-
-  if [ "${args[${i}]}" == "pos" ]; then
-    noFilter=false
-    tickerFilter=true
-    posFilter=true
-  fi
-
-  if [ "${args[${i}]}" == "last-price" ]; then
-    noFilter=false
-    tickerFilter=true
-    lastPriceFilter=true
-  fi
-
-  if [ "${args[${i}]}" == "hist-ord" ]; then
-    noFilter=false
-    tickerFilter=true
-    histOrdFilter=true
-  fi
-
-  if [ "${args[${i}]}" == "graph-pos" ]; then
-    noFilter=false
-    tickerFilter=true
-    graphPosFilter=true
-  fi
-
+#reads command line arguments
+while [ "$#" -gt 0 ]
+do
+   if [ $1 = "-t" ]
+   then
+      ticker_filter="$ticker_filter$2\|"
+      shift
+   elif [ $1 = "-a" ]
+   then
+      daytime_after="$2"
+      shift
+   elif [ $1 = "-b" ]
+   then
+      daytime_before="$2"
+      shift
+   elif [ $1 = "list-tick" ] || [ $1 = "profit" ] || [ $1 = "pos" ] || [ $1 = "last-price" ] || [ $1 = "hist-ord" ] || [ $1 = "graph-pos" ]
+   then
+      command="$1"
+   elif [ $1 = "-h" ] || [ $1 = "--help" ]
+   then
+      help
+      exit 0
+   elif [ $1 = "-w" ]
+   then
+      if [ $2 -gt 0 ] && [ $width = 0 ]
+      then
+         width=$2
+         shift
+      else
+         echo "error: unvalid width entered"
+         exit 1
+      fi
+   elif [[ $1 =~ ".gz" ]]
+   then
+      gz_files=$gz_files" $1"
+   else
+      log_files=$log_files" $1"
+   fi
+   shift
 done
 
-
-#pokud se nezadá žádný filtr, vloží se do eval "cat input.log"... to zapříčiní, že eval neudělá nic navíc (jakoby neexistoval)
-  if [ "$noFilter" == "true" ]; then
-    prikaz=$src
-  fi
-  
-#pokud se nezadá žádný ticker, tak se filtr tickerů poté se vyhodnocovací IF vyhodnotí jako true 
-filtrIF="1>0" 
-if [ ${#tickerArray[@]} -gt 0 ]; then
-    filtrIF="" 
-  fi
-
-if [ "$tickerFilter" == "true" ]; then
-    
-    #skládání ticker filtru do promenne prikaz
-    prikaz="awk" #neměnný začátek
-
-    #nahrání proměnných z tickerArray do -v (lokální proměnné fce AWK)
-    for (( i=0;i<${#tickerArray[@]};i++)); do
-      prikaz+=" -v ticker$i=\${tickerArray[$i]}"
-    done
-
-    prikaz+=" -F ';' '{if( " #neměnné uložení delimu a začátek IFu
-
-    #nahrání podmínek do IFu
-    for (( i=0;i<${#tickerArray[@]};i++)); do
-      if [ $i != 0 ]; then
-        prikaz+=" || "
-      fi
-      prikaz+="\$2 == ticker$i "
-    
-    done
-
-    prikaz+="$filtrIF $filtrDate ) print \$$printCol;}'" #neměnné ukončení příkazu
+#creates ticker filter
+if [ "$ticker_filter" = "" ]
+then
+   ticker_filter="cat"
+else
+   ticker_filter="grep -w \"$ticker_filter  \""
 fi
 
-#jednotlivé příkazy se do finálního příkazu nahrávají až po profiltrovaní
-if [ "$profitFilter" == "true" ]; then
-    prikaz+=" | awk -F ';' '{if( \$3 == \"sell\" ) {sellSum+=(\$4*\$6) } else {buySum+=(\$4*\$6) } }  END{ celkem=(sellSum-buySum) ; printf (\"%.2f\n\", celkem) }'"
-  fi
+#creates daytime filters
+daytime_after="awk -F ';' -v date=\""$daytime_after"\" '{if(date < \$1){print}}'"
+daytime_before="awk -F ';' -v date=\""$daytime_before"\" '{if(date > \$1){print}}'"
 
-if [ "$posFilter" == "true" ]; then
-  prikaz+=" | awk -F ';' ' { if(\$3==\"buy\") { a[\$2]+=\$6 } else { a[\$2]-=\$6 } lastPrice[\$2]=\$4 } END { maxLength=0; for(i in a) { currValue=a[i]*lastPrice[i]; currString=sprintf(\"%.2f\", currValue); if(maxLength<length(currString) ) { maxLength=length(currString); } } maxLength=maxLength+1; for(i in a) { printf(\"%-10s:%*.2f\n\",i,maxLength,(a[i]*lastPrice[i]) ) } }' | sort -t ':' -k 2 -g -r"
+#connects all filters and creates beginning for every command (reads files and filteres them)
+filter="$ticker_filter | $daytime_after | $daytime_before"
+read_files="zcat $log_files $gz_files | sort"
+command_start="$read_files | $filter"
+
+#makes commands happen
+if [ "$command" = "list-tick" ]
+then
+   eval $command_start | awk -F ';' '{printf $2"\n"}' | sort | uniq
+elif [ "$command" = "profit" ]
+then
+   eval $command_start | awk -F ';' 'BEGIN{ ahoj=0.00 } {$3=="buy" ? ahoj=ahoj-($4*$6) : ahoj=ahoj+($4*$6)} END { printf "%.2f\n", ahoj }'
+elif [ "$command" = "pos" ]
+then
+   eval $command_start | sort -t ';' -k 2,2 -k 1,1 | awk -F ';' -v curTicker="" -v lastPrice=0 -v value=0 '{if($2 != curTicker && curTicker != "")
+   {printf "%s %.2f\n", curTicker, value*lastPrice;value=0};lastPrice=$4;curTicker=$2;$3 == "buy" ? value += $6 : value -= $6} END{printf "%s %.2f\n", curTicker, value*lastPrice}' | sort -t ':' -n -r -k 2,2 | awk -F ' ' -v maxlength=0 '
+   {print;if(length($2)>maxlength){maxlength=length($2)}}END{printf "%d\n",maxlength}' | sort | awk -F ' ' -v maxlength=0 '{if(maxlength==0){maxlength=$1}else{printf "%-10s:%*.2f\n",$1, maxlength + ($2=="" ? 0 : 1), $2}}' | sort -t ':' -n -r -k 2,2
+elif [ "$command" = "last-price" ]
+then
+   eval $command_start | sort -t ';' -k 2,2 -r -k 1,1 | awk -F ';' -v curTicker="" -v lastPrice=0 '{if($2 != curTicker){curTicker = $2;lastPrice = $4;printf "%s %.2f\n", curTicker,lastPrice}}' | awk -F ' ' -v maxlength=0 '
+   {print;if(length($2)>maxlength){maxlength=length($2)}}END{printf "%d\n",maxlength}' | sort | awk -F ' ' -v maxlength=0 '{if(maxlength==0){maxlength=$1}else{printf "%-10s:%*.2f\n",$1, maxlength + ($2=="" ? 0 : 1), $2}}'
+elif [ "$command" = "hist-ord" ]
+then
+   eval $command_start | sort -t ';' -k 2,2 | awk -F ';' -v curTicker="" -v width=0 -v count=0 '{width=0;if($2 != curTicker && curTicker != "")
+   {printf "%s ", curTicker;while(count!=0){width++;count -= 1};printf"%d\n",width};curTicker=$2;count+=1} 
+   END{width=0;printf "%s ", curTicker;while(count!=0){width++;count -= 1};printf"%d\n",width}' | sort -n -r -k 2,2 | awk -F ' ' -v width=$width -v divide=0 -v count=0 '
+   {printf"%-10s: ",$1;if(divide==0&&width!=0){divide=$2/width}else if(divide==0&&width==0){divide=1};count=($2/divide);while(count>0){printf "#";count--;};printf "\n"}' | sort
+elif [ "$command" = "graph-pos" ]
+then
+   eval $command_start | sort -t ';' -k 2,2 -k 1,1 | awk -F ';' -v curTicker="" -v lastPrice=0 -v value=0 '{if($2 != curTicker && curTicker != "")
+   {printf "%s %.2f\n", curTicker, value*lastPrice;value=0};lastPrice=$4;curTicker=$2;$3 == "buy" ? value += $6 : value -= $6} END{printf "%s %.2f\n", curTicker, value*lastPrice}' | sort -t ':' -n -r -k 2,2 | awk -F ' ' -v maxnumber=0 '
+   {print;if($2>maxnumber){maxnumber=$2}else if(-1*$2>maxnumber){maxnumber=-1*$2}}END{printf "%d\n",maxnumber}' | sort | awk -F ' ' -v width=$width -v divide=0 -v maxnumber=0 -v count=0 '{if(maxnumber==0){maxnumber=$1}else{printf"%-10s:",$1;if(divide==0&&width!=0)
+   {divide=maxnumber/width}else if(divide==0&&width==0){divide=1};count=($2/divide);if(count>=1||count<=-1){printf " "};if($2>0){while(count>=1){printf "#";count--;}}else{while(count<=-1){printf "!";count++;}};printf "\n"}}' | sort
+else
+   eval $command_start
 fi
 
-if [ "$lastPriceFilter" == "true" ]; then
-  prikaz+=" | awk -F ';' '{a[\$2]=\$4}END{maxLength=0; for(i in a) {if(maxLength<length(a[i]) ) {maxLength=length(a[i]);  } } for(i in a) printf(\"%-10s: %*.2f\n\",i,maxLength,a[i] )}' | sort -t ':' -k 1"
-fi
-
-if [ "$histOrdFilter" == "true" ]; then
-  prikaz+=" | awk -F ';' '{a[\$2]=a[\$2]\"#\";}END{for(i in a) {if (a[i]==\"\") {printf(\"PICOVINKA\n\");} printf(\"%-10s: %s\n\",i,a[i]);} }' | sort  -k 1 "
-fi
-
-if [ "$graphPosFilter" == "true" ]; then
-  prikaz+=" | awk -F ';' -v width="$width" 'function abs(x){return ((x < 0.0) ? -x : x)} { if(\$3==\"buy\") {a[\$2]+=\$6} else {a[\$2]-=\$6} lastPrice[\$2]=\$4 } END { if(width!=\"\") {for(i in a) { if(max==\"\") { max=abs(a[i]*lastPrice[i]); } if(abs(a[i]*lastPrice[i])>max) { max=abs(a[i]*lastPrice[i]); } } max=max/width;} else {max=1000;} for(i in a) { pocet=int((a[i]*lastPrice[i]) / max); a[i]=\"\"; for(j = 0; j < pocet; j++) {a[i]=a[i]\"#\"} for(j=0;j>pocet;j--) {a[i]=a[i]\"!\"} if(a[i]==\"\") {printf(\"%-10s:%s\n\",i,a[i] )} else {printf(\"%-10s: %s\n\",i,a[i] )} } }' | sort -t ':' -k 1 "
-
-fi
-
-if [ "$listTick" == "true" ]; then
-  prikaz+=" | sort | uniq" # musí se seřadit a pak se zavolá uniq, který vytiskne jen unikátní prvky
-fi
-
-#finální volání příkazů
-eval "$src" | eval "$prikaz" 
+exit 0
